export const CALL_ELEVATOR_FROM_FLOOR = "CALL_ELEVATOR_FROM_FLOOR"
export const CHANGE_ELEVATOR_FLOOR_IN_ELEVATOR = "CHANGE_ELEVATOR_FLOOR_IN_ELEVATOR"
export const MOVING_ELEVATOR = "MOVING_ELEVATOR"

export const CHANGE_ELEVATOR_FLOOR_IN_SECOND_ELEVATOR = "CHANGE_ELEVATOR_FLOOR_IN_SECOND_ELEVATOR"
export const MOVING_SECOND_ELEVATOR = "MOVING_SECOND_ELEVATOR"