export const CALL_ELEVATOR_FROM_FLOOR = "CALL_ELEVATOR_FROM_FLOOR" as const
export const CHANGE_ELEVATOR_FLOOR_IN_ELEVATOR = "CHANGE_ELEVATOR_FLOOR_IN_ELEVATOR" as const
export const MOVING_ELEVATOR = "MOVING_ELEVATOR" as const

const elevatorTypes = {
    CALL_ELEVATOR_FROM_FLOOR, CHANGE_ELEVATOR_FLOOR_IN_ELEVATOR, MOVING_ELEVATOR
}

export type ELEVATOR_TYPES = typeof elevatorTypes[keyof typeof elevatorTypes]